version: '3.7'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - db

  worker:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
